# Generated by Django 3.1.8 on 2021-05-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='name',
        ),
    ]
